
// (c) 2025 Kazuki Kohzuki

namespace EnumSerializer.Generators;

[Generator(LanguageNames.CSharp)]
internal sealed class AttributesGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static context =>
        {
            context.AddSource("EnumSerializableAttribute.g.cs", EnumSerializableSource);
            context.AddSource("SerializeValueAttribute.g.cs", SerializeValueSource);
            context.AddSource("DefaultSerializeValueAttribute.g.cs", DefaultSerializeValueSource);
        });
    } // public void Initialize (IncrementalGeneratorInitializationContext)

    internal const string Namespace = "EnumSerializer";
    internal const string EnumSerializableName = "EnumSerializableAttribute";
    internal const string SerializeValueName = "SerializeValueAttribute";
    internal const string DefaultSerializeValueName = "DefaultSerializeValueAttribute";

    // TODO: Update "C#-test" to "C#" when the syntax highlighting is officially implemented

    // lang=C#-test
    private const string EnumSerializableSource = """
// <auto-generated/>

#nullable enable

namespace EnumSerializer;

/// <summary>
/// Specifies that the enum is serializable with the specified target attributes.
/// </summary>
[global::System.AttributeUsage(global::System.AttributeTargets.Enum, Inherited = false, AllowMultiple = true)]
internal sealed class EnumSerializableAttribute : global::System.Attribute
{
    /// <summary>
    /// Gets the target attributes for serialization.
    /// </summary>
    internal IReadOnlyList<global::System.Type> Target { get; }

    /// <summary>
    /// Initializes a new instance of the <see cref="EnumSerializableAttribute"/> class.
    /// </summary>
    /// <param name="target">Target attributes for serialization.</param>
    internal EnumSerializableAttribute(params global::System.Type[] target)
    {
        this.Target = target;
    } // ctor (params global::System.Type[])
} // internal sealed class EnumSerializableAttribute : global::System.Attribute
""";

    // lang=C#-test
    private const string SerializeValueSource = """
// <auto-generated/>

#nullable enable

namespace EnumSerializer;

/// <summary>
/// Represents a serialized value of an enum member.
/// </summary>
[global::System.AttributeUsage(global::System.AttributeTargets.Field, Inherited = false, AllowMultiple = true)]
internal abstract class SerializeValueAttribute : global::System.Attribute
{
    /// <summary>
    /// Gets the serialized value.
    /// </summary>
    internal string Value { get; }

    /// <summary>
    /// Initializes a new instance of the <see cref="SerializeValueAttribute"/> class.
    /// </summary>
    /// <param name="value">The serialized value.</param>
    internal SerializeValueAttribute(string value)
    {
        this.Value = value;
    } // ctor (string)
} // internal abstract class SerializeValueAttribute : global::System.Attribute
""";

    // lang=C#-test
    private const string DefaultSerializeValueSource = """
// <auto-generated/>

#nullable enable

namespace EnumSerializer;

/// <summary>
/// Represents a default serialized value of an enum member.
/// </summary>
[global::System.AttributeUsage(global::System.AttributeTargets.Field, Inherited = false, AllowMultiple = false)]
internal class DefaultSerializeValueAttribute : global::EnumSerializer.SerializeValueAttribute
{
    /// <summary>
    /// Initializes a new instance of the <see cref="DefaultSerializeValueAttribute"/> class.
    /// </summary>
    internal DefaultSerializeValueAttribute(string value) : base(value) {}
} // internal class DefaultSerializeValueAttribute : global::EnumSerializer.SerializeValueAttribute
""";
} // internal sealed class AttributesGenerator : IIncrementalGenerator
