
// (c) 2025-2026 Kazuki Kohzuki

using SourceGeneratorUtils;
using System.Collections.Immutable;
using static EnumSerializer.SymbolUtils;

namespace EnumSerializer.Generators;

[Generator(LanguageNames.CSharp)]
internal sealed class SerializerGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "EnumSerializer.EnumSerializableAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var sources = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeFullName,
            static (node, token) => node is EnumDeclarationSyntax,
            static (context, token) => context
        ).Collect();
        context.RegisterSourceOutput(sources, Execute);
    } // public void Initialize (IncrementalGeneratorInitializationContext)

    private static void Execute(SourceProductionContext context, ImmutableArray<GeneratorAttributeSyntaxContext> sources)
    {
        if (sources.Length == 0) return;

        var builder = new StringBuilder();
        builder.Append(@"// <auto-generated/>

#nullable enable
");
        foreach (var type in sources)
        {
            try
            {
                var typeSymbol = (INamedTypeSymbol)type.TargetSymbol;

                var attrs = type.Attributes.Where(a => a.AttributeClass.GetFullName() == AttributeFullName);
                var args =
                    type.Attributes.Where(a => a.AttributeClass.GetFullName() == AttributeFullName)
                                   .Select(GetEnumSerializationInfo)
                                   .OfType<EnumSerializationInfo>()
                                   .Distinct(new EnumSerializationInfo.EqualityComparer());

                if (!args.Any()) continue;

                Generate(builder, typeSymbol, args);
            }
            catch
            {

            }
        }

        context.AddSource("EnumSerializationExtensions.g.cs", builder.NormalizeNewLines().ToString());
    } // private static void Execute (SourceProductionContext, ImmutableArray<GeneratorAttributeSyntaxContext>)

    private static EnumSerializationInfo? GetEnumSerializationInfo(AttributeData arrtibute)
    {
        var args = arrtibute.ConstructorArguments;
        if (args.Length == 0) return default;
        if (args[0].Value is not INamedTypeSymbol enumType) return default;

        var caseSensitive = true;
        var namedArgs = arrtibute.NamedArguments;
        var caseSensitiveArg = namedArgs.FirstOrDefault(kv => kv.Key == "CaseSensitive");
        if (caseSensitiveArg.Value.Value is bool cs)
            caseSensitive = cs;

        return new(enumType, caseSensitive);
    } // private static EnumSerializationInfo GetEnumSerializationInfo (AttributeData)

    private static void Generate(StringBuilder builder, INamedTypeSymbol enumType, IEnumerable<EnumSerializationInfo> targetTypes)
    {
        var enumShortName = enumType.Name;
        var enumName = enumType.GetFullyQualifiedName();

        var ns = enumType.ContainingNamespace.ToDisplayString();

        builder.AppendLine($$"""

namespace {{ns}}
{
    /// <summary>
    /// Provides extension methods for serialization of the <see cref="{{enumName}}"/> enum.
    /// </summary>
    internal static class {{enumType.Name}}SerializationExtensions
    {
        /// <summary>
        /// Serializes the specified <see cref="{{enumName}}"/> value to a string using the specified serialization attribute.
        /// </summary>
        /// <typeparam name="TAttr">The serialization attribute type.</typeparam>
        /// <param name="value">The <see cref="{{enumName}}"/> value to serialize.</param>
        /// <returns>The serialized string representation of the enum value.</returns>
        internal static string ToString<TAttr>(this {{enumName}} value) where TAttr : global::EnumSerializer.SerializeValueAttribute
        {
""");

        foreach (var target in targetTypes)
            GenerateToString(builder, target.EnumType);

        builder.AppendLine($$"""
            // Fallback to default ToString() if no matching attribute type is found
            return value.ToString();
        } // internal static string ToString<TAttr>(this {{enumName}}) where TAttr : global::EnumSerializer.SerializeValueAttribute
""");

        foreach (var target in targetTypes)
            GenerateSpecialToString(builder, enumName, enumType, target.EnumType);

        builder.AppendLine($$"""

        /// <summary>
        /// Deserializes the specified string to a <see cref="{{enumName}}"/> value using the specified serialization attribute.
        /// </summary>
        /// <typeparam name="TAttr">The serialization attribute type.</typeparam>
        /// <param name="text">The string representation of the enum value.</param>
        /// <returns>The deserialized <see cref="{{enumName}}"/> value.</returns>
        internal static {{enumName}} Get{{enumType.Name}}FromString<TAttr>(this global::System.ReadOnlySpan<char> text) where TAttr : global::EnumSerializer.SerializeValueAttribute
        {
""");

        foreach (var target in targetTypes)
            GenerateFromString(builder, target.EnumType, enumShortName);

        builder.AppendLine($$"""
            // Fallback to default Enum.Parse if no matching attribute type is found
            return ({{enumName}})global::System.Enum.Parse(typeof({{enumName}}), text);
        } // internal static {{enumName}} Get{{enumType.Name}}FromString<TAttr>(this global::System.ReadOnlySpan<char>) where TAttr : global::EnumSerializer.SerializeValueAttribute
""");

        foreach (var target in targetTypes)
            GenerateFromString(builder, enumName, enumType, target);


        builder.AppendLine($$"""

        /// <summary>
        /// Deserializes the specified string to a <see cref="{{enumName}}"/> value using the specified serialization attribute.
        /// </summary>
        /// <typeparam name="TAttr">The serialization attribute type.</typeparam>
        /// <param name="text">The string representation of the enum value.</param>
        /// <returns>The deserialized <see cref="{{enumName}}"/> value.</returns>
        internal static bool TryParse{{enumType.Name}}<TAttr>(this global::System.ReadOnlySpan<char> text, out {{enumName}} value) where TAttr : global::EnumSerializer.SerializeValueAttribute
        {
""");
        foreach (var target in targetTypes)
            GenerateTryParse(builder, target.EnumType, enumShortName);

        builder.AppendLine($$"""
            // No matching attribute type found
            value = default;
            return false;
        } // internal static bool TryParse{{enumType.Name}}<TAttr>(this global::System.ReadOnlySpan<char>, out {{enumName}}) where TAttr : global::EnumSerializer.SerializeValueAttribute
""");

        foreach (var target in targetTypes)
            GenerateTryParse(builder, enumName, enumType, target);

        builder.AppendLine($$"""
    } // internal static class {{enumType.Name}}SerializationExtensions
} // namespace {{ns}}
""");
    } // private static void Generate (StringBuilder, INamedTypeSymbol, IEnumerable<INamedTypeSymbol>)

    #region ToString

    private static void GenerateToString(StringBuilder builder, INamedTypeSymbol target)
    {
        if (!CheckInheritance(target, "EnumSerializer.SerializeValueAttribute"))
            return;

        var targetFullName = target.GetFullyQualifiedName();
        builder.AppendLine($$"""
            if (typeof(TAttr) == typeof({{targetFullName}}))
                return {{GetSpecialToStringMethodName(target)}}(value);

""");
    } // private static void GenerateToString (StringBuilder, INamedTypeSymbol)

    private static void GenerateSpecialToString(StringBuilder builder, string enumName, INamedTypeSymbol enumType, INamedTypeSymbol target)
    {
        if (!CheckInheritance(target, "EnumSerializer.SerializeValueAttribute"))
            return;

        var targetName = target.GetFullName();
        var targetFullName = target.GetFullyQualifiedName();
        var methodName = GetSpecialToStringMethodName(target);

        builder.AppendLine($$"""

        /// <summary>
        /// Serializes the specified <see cref="{{enumName}}"/> value to a string using the <see cref="{{targetFullName}}"/> attribute.
        /// </summary>
        /// <param name="value">The <see cref="{{enumName}}"/> value to serialize.</param>
        /// <returns>The serialized string representation of the enum value.</returns>
        internal static string {{methodName}}(this {{enumName}} value)
        {
            return value switch
            {
""");

        var fields = enumType.GetMembers().OfType<IFieldSymbol>().Where(f => f.IsStatic);
        var cases = new Dictionary<string, string>();
        var length = 0;
        foreach (var field in fields)
        {
            var attr = field.GetAttributes().FirstOrDefault(a => a.AttributeClass.GetFullName() == targetName);
            if (attr is null) continue;
            var args = attr.ConstructorArguments;
            if (args.Length == 0) continue;
            var serializedValue = args[0].Value?.ToString() ?? string.Empty;
            var key = $"{enumName}.{field.Name}";
            cases.Add(key, serializedValue);
            if (key.Length > length)
                length = key.Length;
        }

        foreach ((var key, var value) in cases)
        {
            builder.Append($"\t\t\t\t{key}");
            builder.Append(' ', length - key.Length);
            var s_value = string.IsNullOrEmpty(value) ? "string.Empty" : $"\"{value}\"";
            builder.AppendLine($" => {s_value},");
        }

        builder.AppendLine($$"""
                _ => value.ToString(),
            };
        } // internal static string {{methodName}} (this {{enumName}})
""");
    } // private static void GenerateSpecialToString (StringBuilder, string, INamedTypeSymbol, INamedTypeSymbol)

    private static string GetSpecialToStringMethodName(INamedTypeSymbol target)
    {
        const string Suffix = "Attribute";

        var name = target.Name;
        if (name.EndsWith(Suffix))
            name = name[..^Suffix.Length];
        return $"To{name}";
    } // private static string GetSpecialToStringMethodName (INamedTypeSymbol)

    #endregion ToString

    #region FromString

    private static void GenerateFromString(StringBuilder builder, INamedTypeSymbol target, string enumName)
    {
        if (!CheckInheritance(target, "EnumSerializer.SerializeValueAttribute"))
            return;

        var targetFullName = target.GetFullyQualifiedName();
        builder.AppendLine($$"""
            if (typeof(TAttr) == typeof({{targetFullName}}))
                return {{GetSpecialFromStringMethodName(target, enumName)}}(text);

""");
    } // private static void GenerateFromString (StringBuilder, INamedTypeSymbol, string)

    private static void GenerateFromString(StringBuilder builder, string enumName, INamedTypeSymbol enumType, EnumSerializationInfo info)
    {
        var target = info.EnumType;
        if (!CheckInheritance(target, "EnumSerializer.SerializeValueAttribute"))
            return;

        var targetName = target.GetFullName();
        var targetFullName = target.GetFullyQualifiedName();
        var methodName = GetSpecialFromStringMethodName(target, enumType.Name);

        var cs = info.CaseSensitive;

        var fields = enumType.GetMembers().OfType<IFieldSymbol>().Where(f => f.IsStatic);
        var cases = new Dictionary<string, string>();
        var length = 0;
        foreach (var field in fields)
        {
            var attr = field.GetAttributes().FirstOrDefault(a => a.AttributeClass.GetFullName() == targetName);
            if (attr is null) continue;
            var args = attr.ConstructorArguments;
            if (args.Length == 0) continue;
            var serializedValue = args[0].Value?.ToString() ?? string.Empty;
            if (!cs) serializedValue = serializedValue.ToLowerInvariant();
            if (cases.ContainsKey(serializedValue))
                continue;
            var value = $"{enumName}.{field.Name}";
            cases.Add(serializedValue, value);
            if (serializedValue.Length > length)
                length = serializedValue.Length;
        }

        var comment = cs ? "Comparison is case-sensitive." : "Comparison is case-insensitive.";

        builder.AppendLine($$"""

        /// <summary>
        /// Deserializes the specified string to a <see cref="{{enumName}}"/> value using the <see cref="{{targetFullName}}"/> attribute.
        /// {{comment}}
        /// </summary>
        /// <param name="text">The string representation of the enum value.</param>
        /// <returns>The deserialized <see cref="{{enumName}}"/> value.</returns>
        internal static {{enumName}} {{methodName}}(this global::System.ReadOnlySpan<char> text)
        {
            if (text.Length > {{length}})
                return ({{enumName}})global::System.Enum.Parse(typeof({{enumName}}), text);

""");
        if (cs)
        {
            builder.AppendLine($$"""
            return text switch
            {
""");
        }
        else
        {
            builder.AppendLine($$"""
            // `text.Length` never exceeds {{length}} here
            var lowerBuffer = (stackalloc char[text.Length]);
            text.ToLowerInvariant(lowerBuffer);

            return lowerBuffer switch
            {
""");
        }

        foreach ((var key, var value) in cases)
        {
            builder.Append($"                \"{key}\"");
            builder.Append(' ', length - key.Length);
            builder.AppendLine($" => {value},");
        }

        builder.AppendLine($$"""
                            _ => ({{enumName}})global::System.Enum.Parse(typeof({{enumName}}), text),
                        };
                    } // internal static {{enumName}} {{methodName}} (this global::System.ReadOnlySpan<char>)
            """);
    } // private static void GenerateFromString (StringBuilder, string, INamedTypeSymbol, INamedTypeSymbol)

    private static string GetSpecialFromStringMethodName(INamedTypeSymbol target, string enumName)
    {
        var name = target.Name;
        if (name.EndsWith("Attribute"))
            name = name[..^"Attribute".Length];
        return $"Get{enumName}From{name}";
    } // private static string GetSpecialFromStringMethodName (INamedTypeSymbol, string)

    #endregion FromString

    #region TryParse

    private static void GenerateTryParse(StringBuilder builder, INamedTypeSymbol target, string enumName)
    {
        if (!CheckInheritance(target, "EnumSerializer.SerializeValueAttribute"))
            return;

        var targetFullName = target.GetFullyQualifiedName();
        builder.AppendLine($$"""
            if (typeof(TAttr) == typeof({{targetFullName}}))
                return {{GetTryParseMethodName(target, enumName)}}(text, out value);

""");
    } // private static void GenerateTryParse (StringBuilder, INamedTypeSymbol, string)

    private static void GenerateTryParse(StringBuilder builder, string enumName, INamedTypeSymbol enumType, EnumSerializationInfo info)
    {
        var target = info.EnumType;
        if (!CheckInheritance(target, "EnumSerializer.SerializeValueAttribute"))
            return;

        var targetName = target.GetFullName();
        var targetFullName = target.GetFullyQualifiedName();
        var methodName = GetTryParseMethodName(target, enumType.Name);

        var cs = info.CaseSensitive;

        var fields = enumType.GetMembers().OfType<IFieldSymbol>().Where(f => f.IsStatic);
        var cases = new Dictionary<string, string>();
        var length = 0;
        foreach (var field in fields)
        {
            var attr = field.GetAttributes().FirstOrDefault(a => a.AttributeClass.GetFullName() == targetName);
            if (attr is null) continue;
            var args = attr.ConstructorArguments;
            if (args.Length == 0) continue;
            var serializedValue = args[0].Value?.ToString() ?? string.Empty;
            if (!cs) serializedValue = serializedValue.ToLowerInvariant();
            if (cases.ContainsKey(serializedValue))
                continue;
            cases.Add(serializedValue, field.Name);
            if (serializedValue.Length > length)
                length = serializedValue.Length;
        }

        var comment = cs ? "Comparison is case-sensitive." : "Comparison is case-insensitive.";

        builder.AppendLine($$"""

        /// <summary>
        /// Attempts to deserialize the specified string to a <see cref="{{enumName}}"/> value using the <see cref="{{targetFullName}}"/> attribute.
        /// {{comment}}
        /// </summary>
        /// <param name="text">The string representation of the enum value.</param>
        /// <param name="value">When this method returns, contains the deserialized <see cref="{{enumName}}"/> value if the parsing succeeded, or the default value if the parsing failed.</param>
        /// <returns><see langword="true"/> if the parsing succeeded; otherwise, <see langword="false"/>.</returns>
        internal static bool {{methodName}}(this global::System.ReadOnlySpan<char> text, out {{enumName}} value)
        {
            if (text.Length > {{length}})
                goto ParseFailed;

""");
        if (cs)
        {
            builder.AppendLine($$"""
            switch (text)
            {
""");
        }
        else
        {
            builder.AppendLine($$"""
            // `text.Length` never exceeds {{length}} here
            var lowerBuffer = (stackalloc char[text.Length]);
            text.ToLowerInvariant(lowerBuffer);

            switch (lowerBuffer)
            {
""");
        }

        foreach ((var key, var value) in cases)
        {
            builder.AppendLine($"                case \"{key}\":"); ;
            builder.AppendLine($"                    value = {enumName}.{value};");
            builder.AppendLine($"                    return true;");
        }

        builder.AppendLine($$"""
            }

        ParseFailed:
            value = default;
            return false;
        } // internal static bool {{methodName}}(this global::System.ReadOnlySpan<char>, out {{enumName}})
""");
    } // private static void GenerateTryParse (StringBuilder, string, INamedTypeSymbol, INamedTypeSymbol)

    private static string GetTryParseMethodName(INamedTypeSymbol target, string enumName)
    {
        var name = target.Name;
        if (name.EndsWith("Attribute"))
            name = name[..^"Attribute".Length];
        return $"TryParse{enumName}From{name}";
    } // private static string GetTryParseMethodName (INamedTypeSymbol, string)

    #endregion TryParse
} // internal sealed class SerializerGenerator : IIncrementalGenerator
