
// (c) 2024-2026 Kazuki Kohzuki

namespace SourceGeneratorUtils;

[Generator(LanguageNames.CSharp)]
internal sealed class RoslynUtilsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static context =>
        {
            context.AddSource("RoslynUtils.g.cs", RoslynUtilsSource);
        });
    } // public void Initialize (IncrementalGeneratorInitializationContext)

    // lang=C#
    private const string RoslynUtilsSource = """
// <auto-generated/>

#nullable enable

using Microsoft.CodeAnalysis.Diagnostics;

namespace SourceGeneratorUtils;

/// <summary>
/// Provides extension methods for Roslyn APIs.
/// </summary>
internal static class RoslynUtils
{
    #region Symbol name

    /// <summary>
    /// Gets the fully qualified name of the attribute.
    /// </summary>
    /// <param name="attribute">The attribute.</param>
    /// <param name="context">The context.</param>
    /// <returns>The fully qualified name.</returns>
    internal static string GetGetFullyQualifiedName(this AttributeSyntax attribute, SyntaxNodeAnalysisContext context)
    {
        var symbol = context.SemanticModel.GetSymbolInfo(attribute).Symbol;
        return symbol?.GetFullName() ?? string.Empty;
    } // internal static string GetGetFullyQualifiedName (AttributeSyntax, SyntaxNodeAnalysisContext)

    /// <summary>
    /// Gets the full name of a named type symbol.
    /// </summary>
    /// <param name="symbol">The named type symbol.</param>
    /// <returns>The full name of the symbol without 'global::'.</returns>
    internal static string? GetFullName(this ISymbol? symbol)
        => symbol?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Omitted));

    /// <summary>
    /// Obtains the fully qualified name of the class, including 'global::' prefix.
    /// </summary>
    /// <param name="symbol">The symbol.</param>
    /// <returns>The fully qualified name.</returns>
    internal static string GetFullyQualifiedName(this ISymbol symbol)
        => symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Included));

    #endregion Symbol name

    #region Attribute argument

    /// <summary>
    /// Tries to get the value of a named argument from an attribute.
    /// </summary>
    /// <typeparam name="T">The expected type of the argument value.</typeparam>
    /// <param name="attribute">The attribute data.</param>
    /// <param name="argumentName">The name of the argument to retrieve.</param>
    /// <param name="value">When this method returns, contains the value of the named argument if found and successfully cast to the expected type; otherwise, the default value of <typeparamref name="T"/>.</param>
    /// <returns><see langword="true"/> if the named argument is found and its value can be cast to the expected type; otherwise, <see langword="false"/>.</returns>
    internal static bool TryGetNamedArgumentValue<T>(this AttributeData attribute, string argumentName, out T? value)
    {
        foreach (var namedArg in attribute.NamedArguments)
        {
            if (namedArg.Key != argumentName) continue;
            if (namedArg.Value.Value is not T typedValue) break; // If the argument exists but cannot be cast to the expected type, treat it as not found.
            value = typedValue;
            return true;
        }
        value = default;
        return false;
    } // internal static bool TryGetNamedArgumentValue<T> (this AttributeData, string, out T)

    #endregion Attribute argument
} // internal static class SyntaxNodeUtils
""";
} // internal sealed class RoslynUtilsGenerator : IIncrementalGenerator
