
// (c) 2024-2026 Kazuki Kohzuki

namespace SourceGeneratorUtils;

[Generator(LanguageNames.CSharp)]
internal sealed class RoslynUtilsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static context =>
        {
            context.AddSource("RoslynUtils.g.cs", RoslynUtilsSource);
        });
    } // public void Initialize (IncrementalGeneratorInitializationContext)

    // lang=C#
    private const string RoslynUtilsSource = """
// <auto-generated/>

#nullable enable

using Microsoft.CodeAnalysis.Diagnostics;

namespace SourceGeneratorUtils;

/// <summary>
/// Provides extension methods for Roslyn APIs.
/// </summary>
internal static class RoslynUtils
{
    /// <summary>
    /// Gets the fully qualified name of the attribute.
    /// </summary>
    /// <param name="attribute">The attribute.</param>
    /// <param name="context">The context.</param>
    /// <returns>The fully qualified name.</returns>
    internal static string GetGetFullyQualifiedName(this AttributeSyntax attribute, SyntaxNodeAnalysisContext context)
    {
        var symbol = context.SemanticModel.GetSymbolInfo(attribute).Symbol;
        return symbol?.GetFullName() ?? string.Empty;
    } // internal static string GetGetFullyQualifiedName (AttributeSyntax, SyntaxNodeAnalysisContext)

    /// <summary>
    /// Gets the full name of a named type symbol.
    /// </summary>
    /// <param name="symbol">The named type symbol.</param>
    /// <returns>The full name of the symbol without 'global::'.</returns>
    internal static string? GetFullName(this ISymbol? symbol)
        => symbol?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Omitted));

    /// <summary>
    /// Obtains the fully qualified name of the class, including 'global::' prefix.
    /// </summary>
    /// <param name="symbol">The symbol.</param>
    /// <returns>The fully qualified name.</returns>
    internal static string GetFullyQualifiedName(this ISymbol symbol)
        => symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Included));
} // internal static class SyntaxNodeUtils
""";
} // internal sealed class RoslynUtilsGenerator : IIncrementalGenerator
