
// (c) 2024-2025 Kazuki KOHZUKI

namespace SourceGeneratorUtils;

[Generator(LanguageNames.CSharp)]
internal sealed class StringUtilsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static context =>
        {
            context.AddSource("StringUtils.g.cs", StringUtilsSource);
        });
    } // public void Initialize (IncrementalGeneratorInitializationContext)

    // TODO: Update "C#-test" to "C#" when the syntax highlighting is officially implemented

    // lang=C#-test
    private const string StringUtilsSource = """
// <auto-generated/>

namespace SourceGeneratorUtils;

/// <summary>
/// Provides extension methods for <see cref="string"/>.
/// </summary>
internal static class StringUtils
{
    /// <summary>
    /// Normalizes new lines.
    /// </summary>
    /// <param name="text">The text.</param>
    /// <returns>The normalized text.</returns>
    internal static string NormalizeNewLines(this string text)
        => text.Replace("\r\n", "\n").Replace("\r", "\n").Replace("\n", "\r\n");

    /// <summary>
    /// Normalizes new lines.
    /// </summary>
    /// <param name="builder">The string builder.</param>
    /// <returns>The normalized string builder.</returns>
    internal static StringBuilder NormalizeNewLines(this StringBuilder builder)
        => builder.Replace("\r\n", "\n").Replace("\r", "\n").Replace("\n", "\r\n");
} // internal static class StringUtils
""";
} // internal sealed class StringUtilsGenerator : IIncrementalGenerator
