
/*
 * Generated by JsonTemplateMaker
 *
 * The effect of the JsonTemplateMaker license does not extend to this code,
 * which is a deliverable of JsonTemplateMaker. Therefore, no JsonTemplateMaker
 * license is required to use, copy, modify, merge, publish, distribute,
 * sublicense, and/or sell this generated code.
 */

using System.Text.Json;
using System.Text.Json.Serialization;

namespace TAFitting.Update;

/// <summary>
/// Represents ReleaseInfoJson.
/// </summary>
public sealed class ReleaseInfoJson
{
    /// <summary>
    /// Gets or sets the url.
    /// </summary>
    [JsonPropertyName("url")]
    public string? Url { get; set; }

    /// <summary>
    /// Gets or sets the assets_url.
    /// </summary>
    [JsonPropertyName("assets_url")]
    public string? AssetsUrl { get; set; }

    /// <summary>
    /// Gets or sets the upload_url.
    /// </summary>
    [JsonPropertyName("upload_url")]
    public string? UploadUrl { get; set; }

    /// <summary>
    /// Gets or sets the html_url.
    /// </summary>
    [JsonPropertyName("html_url")]
    public string? HtmlUrl { get; set; }

    /// <summary>
    /// Gets or sets the id.
    /// </summary>
    [JsonPropertyName("id")]
    [JsonNumberHandling(JsonNumberHandling.AllowReadingFromString | JsonNumberHandling.AllowNamedFloatingPointLiterals)]
    public int Id { get; set; }

    /// <summary>
    /// Gets or sets the author.
    /// </summary>
    [JsonPropertyName("author")]
    public JsonAuthorObject? Author { get; set; }

    /// <summary>
    /// Gets or sets the node_id.
    /// </summary>
    [JsonPropertyName("node_id")]
    public string? NodeId { get; set; }

    /// <summary>
    /// Gets or sets the tag_name.
    /// </summary>
    [JsonPropertyName("tag_name")]
    public string? TagName { get; set; }

    /// <summary>
    /// Gets or sets the target_commitish.
    /// </summary>
    [JsonPropertyName("target_commitish")]
    public string? TargetCommitish { get; set; }

    /// <summary>
    /// Gets or sets the name.
    /// </summary>
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    /// <summary>
    /// Gets or sets the draft.
    /// </summary>
    [JsonPropertyName("draft")]
    public bool Draft { get; set; }

    /// <summary>
    /// Gets or sets the immutable.
    /// </summary>
    [JsonPropertyName("immutable")]
    public bool Immutable { get; set; }

    /// <summary>
    /// Gets or sets the prerelease.
    /// </summary>
    [JsonPropertyName("prerelease")]
    public bool Prerelease { get; set; }

    /// <summary>
    /// Gets or sets the created_at.
    /// </summary>
    [JsonPropertyName("created_at")]
    public string? CreatedAt { get; set; }

    /// <summary>
    /// Gets or sets the updated_at.
    /// </summary>
    [JsonPropertyName("updated_at")]
    public string? UpdatedAt { get; set; }

    /// <summary>
    /// Gets or sets the published_at.
    /// </summary>
    [JsonPropertyName("published_at")]
    public string? PublishedAt { get; set; }

    /// <summary>
    /// Gets or sets the assets.
    /// </summary>
    [JsonPropertyName("assets")]
    public JsonAssetsElementObject[]? Assets { get; set; }

    /// <summary>
    /// Gets or sets the tarball_url.
    /// </summary>
    [JsonPropertyName("tarball_url")]
    public string? TarballUrl { get; set; }

    /// <summary>
    /// Gets or sets the zipball_url.
    /// </summary>
    [JsonPropertyName("zipball_url")]
    public string? ZipballUrl { get; set; }

    /// <summary>
    /// Gets or sets the body.
    /// </summary>
    [JsonPropertyName("body")]
    public string? Body { get; set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="ReleaseInfoJson"/> class.
    /// </summary>
    public ReleaseInfoJson() { }

    /// <summary>
    /// Creates a new instance of the <see cref="ReleaseInfoJson"/> class from the JSON text.
    /// </summary>
    /// <param name="json">JSON text to parse.</param>
    /// <param name="options">Options to control the behavior during parsing.</param>
    /// <returns>A <see cref="ReleaseInfoJson"/> instance representing the JSON value.</returns>
    /// <exception cref="System.ArgumentNullException">
    /// <paramref name="json"/> is <see langword="null"/>.
    /// </exception>
    /// <exception cref="JsonException">
    /// The JSON is invalid.
    ///
    /// -or-
    ///
    /// There is remaining data in the string beyond a single JSON value.
    /// </exception>
    public static ReleaseInfoJson? LoadJson(string json, JsonSerializerOptions? options = default)
        => JsonSerializer.Deserialize<ReleaseInfoJson>(json, options);

    /// <summary>
    /// Creates a new instance of the <see cref="ReleaseInfoJson"/> class from the UTF-8 encoded text representing a single JSON value.
    /// </summary>
    /// <param name="utf8Json">JSON data to parse.</param>
    /// <param name="options">Options to control the behavior during reading.</param>
    /// <returns>A <see cref="ReleaseInfoJson"/> instance representing the JSON value.</returns>
    /// <exception cref="System.ArgumentNullException">
    /// <paramref name="utf8Json"/> is <see langword="null"/>.
    /// </exception>
    /// <exception cref="JsonException">
    /// The JSON is invalid, or there is remaining data in the Stream.
    /// </exception>
    public static ReleaseInfoJson? LoadJson(System.IO.Stream utf8Json, JsonSerializerOptions? options = default)
        => JsonSerializer.Deserialize<ReleaseInfoJson>(utf8Json, options);

    /// <summary>
    /// Creates a new instance of the <see cref="ReleaseInfoJson"/> class from the JSON text.
    /// </summary>
    /// <param name="json">JSON text to parse.</param>
    /// <param name="options">Options to control the behavior during parsing.</param>
    /// <returns>A <see cref="ReleaseInfoJson"/> instance representing the JSON value.</returns>
    /// <exception cref="System.ArgumentNullException">
    /// <paramref name="json"/> is <see langword="null"/>.
    /// </exception>
    /// <exception cref="JsonException">
    /// The JSON is invalid.
    ///
    /// -or-
    ///
    /// There is remaining data in the string beyond a single JSON value.
    /// </exception>
    public static ReleaseInfoJson? LoadJson(ReadOnlySpan<char> json, JsonSerializerOptions? options = default)
        => JsonSerializer.Deserialize<ReleaseInfoJson>(json, options);

    /// <summary>
    /// Creates a new instance of the <see cref="ReleaseInfoJson"/> class from the UTF-8 encoded text representing a single JSON value.
    /// </summary>
    /// <param name="utf8Json">JSON data to parse.</param>
    /// <param name="options">Options to control the behavior during reading.</param>
    /// <returns>A <see cref="ReleaseInfoJson"/> instance representing the JSON value.</returns>
    /// <exception cref="System.ArgumentNullException">
    /// <paramref name="utf8Json"/> is <see langword="null"/>.
    /// </exception>
    /// <exception cref="JsonException">
    /// The JSON is invalid, or there is remaining data in the Stream.
    /// </exception>
    public static ReleaseInfoJson? LoadJson(ReadOnlySpan<byte> utf8Json, JsonSerializerOptions? options = default)
        => JsonSerializer.Deserialize<ReleaseInfoJson>(utf8Json, options);

    /// <inheritdoc/>
    public override string ToString()
        => JsonSerializer.Serialize(this);

    /// <summary>
    /// Converts the current instance to UTF-8 encoded JSON text and write it to the <see cref="System.IO.Stream"/>.
    /// </summary>
    /// <param name="utf8Json">The UTF-8 <see cref="System.IO.Stream"/> to write to.</param>
    /// <param name="options">Options to control the conversion behavior.</param>
    /// <exception cref="System.ArgumentNullException">
    /// <paramref name="utf8Json"/> is <see langword="null"/>.
    /// </exception>
    public void Serialize(Stream utf8Json, JsonSerializerOptions? options = default)
        => JsonSerializer.Serialize(utf8Json, this, options);

    /// <summary>
    /// Represents a <see cref="Author"/>.
    /// </summary>
    public sealed class JsonAuthorObject
    {
        /// <summary>
        /// Gets or sets the login.
        /// </summary>
        [JsonPropertyName("login")]
        public string? Login { get; set; }

        /// <summary>
        /// Gets or sets the id.
        /// </summary>
        [JsonPropertyName("id")]
        [JsonNumberHandling(JsonNumberHandling.AllowReadingFromString | JsonNumberHandling.AllowNamedFloatingPointLiterals)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the node_id.
        /// </summary>
        [JsonPropertyName("node_id")]
        public string? NodeId { get; set; }

        /// <summary>
        /// Gets or sets the avatar_url.
        /// </summary>
        [JsonPropertyName("avatar_url")]
        public string? AvatarUrl { get; set; }

        /// <summary>
        /// Gets or sets the gravatar_id.
        /// </summary>
        [JsonPropertyName("gravatar_id")]
        public string? GravatarId { get; set; }

        /// <summary>
        /// Gets or sets the url.
        /// </summary>
        [JsonPropertyName("url")]
        public string? Url { get; set; }

        /// <summary>
        /// Gets or sets the html_url.
        /// </summary>
        [JsonPropertyName("html_url")]
        public string? HtmlUrl { get; set; }

        /// <summary>
        /// Gets or sets the followers_url.
        /// </summary>
        [JsonPropertyName("followers_url")]
        public string? FollowersUrl { get; set; }

        /// <summary>
        /// Gets or sets the following_url.
        /// </summary>
        [JsonPropertyName("following_url")]
        public string? FollowingUrl { get; set; }

        /// <summary>
        /// Gets or sets the gists_url.
        /// </summary>
        [JsonPropertyName("gists_url")]
        public string? GistsUrl { get; set; }

        /// <summary>
        /// Gets or sets the starred_url.
        /// </summary>
        [JsonPropertyName("starred_url")]
        public string? StarredUrl { get; set; }

        /// <summary>
        /// Gets or sets the subscriptions_url.
        /// </summary>
        [JsonPropertyName("subscriptions_url")]
        public string? SubscriptionsUrl { get; set; }

        /// <summary>
        /// Gets or sets the organizations_url.
        /// </summary>
        [JsonPropertyName("organizations_url")]
        public string? OrganizationsUrl { get; set; }

        /// <summary>
        /// Gets or sets the repos_url.
        /// </summary>
        [JsonPropertyName("repos_url")]
        public string? ReposUrl { get; set; }

        /// <summary>
        /// Gets or sets the events_url.
        /// </summary>
        [JsonPropertyName("events_url")]
        public string? EventsUrl { get; set; }

        /// <summary>
        /// Gets or sets the received_events_url.
        /// </summary>
        [JsonPropertyName("received_events_url")]
        public string? ReceivedEventsUrl { get; set; }

        /// <summary>
        /// Gets or sets the type.
        /// </summary>
        [JsonPropertyName("type")]
        public string? Type { get; set; }

        /// <summary>
        /// Gets or sets the user_view_type.
        /// </summary>
        [JsonPropertyName("user_view_type")]
        public string? UserViewType { get; set; }

        /// <summary>
        /// Gets or sets the site_admin.
        /// </summary>
        [JsonPropertyName("site_admin")]
        public bool SiteAdmin { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="JsonAuthorObject"/> class.
        /// </summary>
        public JsonAuthorObject() { }
    } // end of class JsonAuthorObject

    /// <summary>
    /// Represents an element of <see cref="Assets"/>.
    /// </summary>
    public sealed class JsonAssetsElementObject
    {
        /// <summary>
        /// Gets or sets the url.
        /// </summary>
        [JsonPropertyName("url")]
        public string? Url { get; set; }

        /// <summary>
        /// Gets or sets the id.
        /// </summary>
        [JsonPropertyName("id")]
        [JsonNumberHandling(JsonNumberHandling.AllowReadingFromString | JsonNumberHandling.AllowNamedFloatingPointLiterals)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the node_id.
        /// </summary>
        [JsonPropertyName("node_id")]
        public string? NodeId { get; set; }

        /// <summary>
        /// Gets or sets the name.
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get; set; }

        /// <summary>
        /// Gets or sets the label.
        /// </summary>
        [JsonPropertyName("label")]
        public object? Label { get; set; }

        /// <summary>
        /// Gets or sets the uploader.
        /// </summary>
        [JsonPropertyName("uploader")]
        public JsonUploaderObject? Uploader { get; set; }

        /// <summary>
        /// Gets or sets the content_type.
        /// </summary>
        [JsonPropertyName("content_type")]
        public string? ContentType { get; set; }

        /// <summary>
        /// Gets or sets the state.
        /// </summary>
        [JsonPropertyName("state")]
        public string? State { get; set; }

        /// <summary>
        /// Gets or sets the size.
        /// </summary>
        [JsonPropertyName("size")]
        [JsonNumberHandling(JsonNumberHandling.AllowReadingFromString | JsonNumberHandling.AllowNamedFloatingPointLiterals)]
        public int Size { get; set; }

        /// <summary>
        /// Gets or sets the digest.
        /// </summary>
        [JsonPropertyName("digest")]
        public object? Digest { get; set; }

        /// <summary>
        /// Gets or sets the download_count.
        /// </summary>
        [JsonPropertyName("download_count")]
        [JsonNumberHandling(JsonNumberHandling.AllowReadingFromString | JsonNumberHandling.AllowNamedFloatingPointLiterals)]
        public int DownloadCount { get; set; }

        /// <summary>
        /// Gets or sets the created_at.
        /// </summary>
        [JsonPropertyName("created_at")]
        public string? CreatedAt { get; set; }

        /// <summary>
        /// Gets or sets the updated_at.
        /// </summary>
        [JsonPropertyName("updated_at")]
        public string? UpdatedAt { get; set; }

        /// <summary>
        /// Gets or sets the browser_download_url.
        /// </summary>
        [JsonPropertyName("browser_download_url")]
        public string? BrowserDownloadUrl { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="JsonAssetsElementObject"/> class.
        /// </summary>
        public JsonAssetsElementObject() { }

        /// <summary>
        /// Represents a <see cref="Uploader"/>.
        /// </summary>
        public sealed class JsonUploaderObject
        {
            /// <summary>
            /// Gets or sets the login.
            /// </summary>
            [JsonPropertyName("login")]
            public string? Login { get; set; }

            /// <summary>
            /// Gets or sets the id.
            /// </summary>
            [JsonPropertyName("id")]
            [JsonNumberHandling(JsonNumberHandling.AllowReadingFromString | JsonNumberHandling.AllowNamedFloatingPointLiterals)]
            public int Id { get; set; }

            /// <summary>
            /// Gets or sets the node_id.
            /// </summary>
            [JsonPropertyName("node_id")]
            public string? NodeId { get; set; }

            /// <summary>
            /// Gets or sets the avatar_url.
            /// </summary>
            [JsonPropertyName("avatar_url")]
            public string? AvatarUrl { get; set; }

            /// <summary>
            /// Gets or sets the gravatar_id.
            /// </summary>
            [JsonPropertyName("gravatar_id")]
            public string? GravatarId { get; set; }

            /// <summary>
            /// Gets or sets the url.
            /// </summary>
            [JsonPropertyName("url")]
            public string? Url { get; set; }

            /// <summary>
            /// Gets or sets the html_url.
            /// </summary>
            [JsonPropertyName("html_url")]
            public string? HtmlUrl { get; set; }

            /// <summary>
            /// Gets or sets the followers_url.
            /// </summary>
            [JsonPropertyName("followers_url")]
            public string? FollowersUrl { get; set; }

            /// <summary>
            /// Gets or sets the following_url.
            /// </summary>
            [JsonPropertyName("following_url")]
            public string? FollowingUrl { get; set; }

            /// <summary>
            /// Gets or sets the gists_url.
            /// </summary>
            [JsonPropertyName("gists_url")]
            public string? GistsUrl { get; set; }

            /// <summary>
            /// Gets or sets the starred_url.
            /// </summary>
            [JsonPropertyName("starred_url")]
            public string? StarredUrl { get; set; }

            /// <summary>
            /// Gets or sets the subscriptions_url.
            /// </summary>
            [JsonPropertyName("subscriptions_url")]
            public string? SubscriptionsUrl { get; set; }

            /// <summary>
            /// Gets or sets the organizations_url.
            /// </summary>
            [JsonPropertyName("organizations_url")]
            public string? OrganizationsUrl { get; set; }

            /// <summary>
            /// Gets or sets the repos_url.
            /// </summary>
            [JsonPropertyName("repos_url")]
            public string? ReposUrl { get; set; }

            /// <summary>
            /// Gets or sets the events_url.
            /// </summary>
            [JsonPropertyName("events_url")]
            public string? EventsUrl { get; set; }

            /// <summary>
            /// Gets or sets the received_events_url.
            /// </summary>
            [JsonPropertyName("received_events_url")]
            public string? ReceivedEventsUrl { get; set; }

            /// <summary>
            /// Gets or sets the type.
            /// </summary>
            [JsonPropertyName("type")]
            public string? Type { get; set; }

            /// <summary>
            /// Gets or sets the user_view_type.
            /// </summary>
            [JsonPropertyName("user_view_type")]
            public string? UserViewType { get; set; }

            /// <summary>
            /// Gets or sets the site_admin.
            /// </summary>
            [JsonPropertyName("site_admin")]
            public bool SiteAdmin { get; set; }

            /// <summary>
            /// Initializes a new instance of the <see cref="JsonUploaderObject"/> class.
            /// </summary>
            public JsonUploaderObject() { }
        } // end of class JsonUploaderObject
    } // end of class JsonAssetsElementObject
} // end of class ReleaseInfoJson
