
// (c) 2024 Kazuki Kohzuki

namespace TAFitting.AvxGenerator.Generators;

[Generator(LanguageNames.CSharp)]
internal sealed class IAvxVectorInterfaceGenerator : ISourceGenerator
{
    internal const string InterfaceName = "IAvxVector";

    public void Initialize(GeneratorInitializationContext context) { }

    public void Execute(GeneratorExecutionContext context)
    {
        context.AddSource($"{InterfaceName}.g.cs", InterfaceSource);
    } // public void Execute (GeneratorExecutionContext)


    private const string InterfaceSource = @"// <auto-generated/>

using System.Numerics;
using System.Runtime.Intrinsics;

#nullable enable

namespace TAFitting.Data;

/// <summary>
/// An AVX vector.
/// </summary>
internal interface IAvxVector<TSelf>
    : IAdditionOperators<TSelf,TSelf,TSelf>, ISubtractionOperators<TSelf,TSelf,TSelf>, IMultiplyOperators<TSelf,TSelf,TSelf>, IDivisionOperators<TSelf,TSelf,TSelf>
    where TSelf : IAvxVector<TSelf>
{
    /// <summary>
    /// Gets the sum of the elements.
    /// </summary>
    double Sum { get; }

    /// <summary>
    /// Creates a new instance of the <see cref=""IAvxVector{TSelf}""/> class
    /// with the specified values.
    /// </summary>
    /// <param name=""values"">The values.</param>
    /// <returns>A new instance of the <see cref=""IAvxVector{TSelf}""/> class with the <paramref name=""values""/>.</returns>
    abstract static TSelf Create(double[] values);

    /// <summary>
    /// Creates a new instance of the <see cref=""IAvxVector{TSelf}""/> class
    /// with the specified length.
    /// </summary>
    /// <param name=""length"">The length.</param>
    /// <returns>A new instance of the <see cref=""IAvxVector{TSelf}""/> class with the <paramref name=""length""/>.</returns>
    abstract static TSelf Create(int length);

    /// <summary>
    /// Gets the capacity.
    /// </summary>
    /// <returns>The capacity.</returns>
    abstract static int GetCapacity();

    /// <summary>
    /// Gets a value indicating whether the current hardware supports AVX.
    /// </summary>
    /// <returns><see langword=""true""/> if the current hardware supports AVX; otherwise, <see langword=""false""/>.</returns>
    abstract static bool CheckSupported();
} // internal interface IAvxVector<TSelf>
";
} // internal sealed class IAvxVectorInterfaceGenerator : ISourceGenerator
