
// (c) 2025 Kazuki Kohzuki

namespace DisposalGenerator.Generators;

[Generator(LanguageNames.CSharp)]
internal sealed class AttributesGenerator : IIncrementalGenerator
{
    internal const string Namespace = "DisposalGenerator";
    internal const string AutoDisposalAttributeName = "AutoDisposalAttribute";
    internal const string DoNotDisposeAttributeName = "DoNotDisposeAttribute";
    internal const string DoNotDisposeAttributeShortName = "DoNotDispose";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static context =>
        {
            context.AddSource("AutoDisposalAttribute.g.cs", AutoDisposalAttributeSource);
            context.AddSource("DoNotDisposeAttribute.g.cs", DoNotDisposeAttribute);
        });
    } // public void Initialize (IncrementalGeneratorInitializationContext)

    private const string AutoDisposalAttributeSource = @"// <auto-generated/>

#nullable enable

namespace DisposalGenerator;

/// <summary>
/// Specifies that the class is automatically disposed.
/// </summary>
[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
internal sealed class AutoDisposalAttribute : global::System.Attribute
{
    /// <summary>
    /// Gets or sets the method name for managed disposal.
    /// </summary>
    public string? UnmanagedDisposalMethod { get; set; }

    /// <summary>
    /// Initializes a new instance of the <see cref=""AutoDisposalAttribute""/> class.
    /// </summary>
    internal AutoDisposalAttribute() { }
} // internal sealed class AutoDisposalAttribute : global::System.Attribute
";

    private const string DoNotDisposeAttribute = @"// <auto-generated/>

#nullable enable

namespace DisposalGenerator;

/// <summary>
/// Specifies that the field must not be disposed automatically.
/// </summary>
[global::System.AttributeUsage(global::System.AttributeTargets.Field, AllowMultiple = false, Inherited = false)]
internal sealed class DoNotDisposeAttribute : global::System.Attribute
{
    /// <summary>
    /// Gets the reason why the field must not be disposed automatically.
    /// </summary>
    public string? Reason { get; }

    /// <summary>
    /// Initializes a new instance of the <see cref=""DoNotDisposeAttribute""/> class.
    /// </summary>
    /// <param name=""reason"">The reason why the field must not be disposed automatically.</param>
    internal DoNotDisposeAttribute(string reason = """")
    {
        this.Reason = reason;
    } // ctor ([string])
} // internal sealed class DoNotDisposeAttribute : global::System.Attribute
";
} // internal sealed class AttributesGenerator : IIncrementalGenerator
