
// (c) 2025 Kazuki Kohzuki

namespace DisposalGenerator.Generators;

[Generator(LanguageNames.CSharp)]
internal sealed class AttributesGenerator : IIncrementalGenerator
{
    internal const string Namespace = "DisposalGenerator";
    internal const string AutoDisposalAttributeName = "AutoDisposalAttribute";
    internal const string NotToBeDisposedAttributeName = "NotToBeDisposedAttribute";
    internal const string NotToBeDisposedAttributeShortName = "NotToBeDisposed";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static context =>
        {
            context.AddSource("AutoDisposalAttribute.g.cs", AutoDisposalAttributeSource);
            context.AddSource("NotToBeDisposedAttribute.g.cs", NotToBeDisposedAttribute);
        });
    } // public void Initialize (IncrementalGeneratorInitializationContext)

    private const string AutoDisposalAttributeSource = @"// <auto-generated/>

using System;

#nullable enable

namespace DisposalGenerator;

/// <summary>
/// Specifies that the class is automatically disposed.
/// </summary>
[AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
internal sealed class AutoDisposalAttribute : Attribute
{
    /// <summary>
    /// Gets or sets the method name for managed disposal.
    /// </summary>
    public string? UnmanagedDisposalMethod { get; set; }

    /// <summary>
    /// Initializes a new instance of the <see cref=""AutoDisposalAttribute""/> class.
    /// </summary>
    internal AutoDisposalAttribute() { }
} // internal sealed class AutoDisposalAttribute : Attribute
";

    private const string NotToBeDisposedAttribute = @"// <auto-generated/>
using System;

#nullable enable

namespace DisposalGenerator;

/// <summary>
/// Specifies that the field must not be disposed automatically.
/// </summary>
[AttributeUsage(AttributeTargets.Field, AllowMultiple = false, Inherited = false)]
internal sealed class NotToBeDisposedAttribute : Attribute
{
    /// <summary>
    /// Initializes a new instance of the <see cref=""NotToBeDisposedAttribute""/> class.
    /// </summary>
    internal NotToBeDisposedAttribute() { }
} // internal sealed class NotToBeDisposedAttribute : Attribute
";
} // internal sealed class AttributesGenerator : IIncrementalGenerator
